name: ncemntqc
dependencies:
  - python=3.7
  - numpy
  - scipy
  - jupyter
  - matplotlib
  - seaborn
  - pip:
    - cvxpy
    - cvxopt
    - pylatexenc
    - qiskit-ibmq-provider==0.9
    - qiskit-terra==0.15.2
    - qiskit-aer==0.6.1
    - qiskit-ignis==0.5
